=== mirkob06/TPSI/esercizi3/film_archive/movie_archive.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="movies">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movie" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string" />
              <xs:element name="title" type="xs:string" />
              <xs:element name="year" type="xs:positiveInteger" />
              <xs:element name="genre" type="xs:string" />
              <xs:element name="duration" type="xs:positiveInteger" />
              <xs:element name="directors" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="director" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="firstName" type="xs:string" />
                          <xs:element name="lastName" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="actors" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="actor" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="firstName" type="xs:string" />
                          <xs:element name="lastName" type="xs:string" />
                          <xs:element name="role" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="reviews" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="review" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="date" type="xs:date" />
                          <xs:element name="rating" type="xs:positiveInteger" />
                          <xs:element name="text" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" use="required" type="xs:string" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mirkob06/TPSI/esercizi3/film_archive/sample_movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="movie_archive.xsd">
  <movie id="FILM-12345">
    <title>Inception</title>
    <year>2010</year>
    <genre>Science Fiction</genre>
    <duration>148</duration>
    <directors>
      <director>
        <firstName>Christopher</firstName>
        <lastName>Nolan</lastName>
      </director>
    </directors>
    <actors>
      <actor>
        <firstName>Leonardo</firstName>
        <lastName>DiCaprio</lastName>
        <role>Dom Cobb</role>
      </actor>
      <actor>
        <firstName>Joseph</firstName>
        <lastName>Gordon-Levitt</lastName>
        <role>Arthur</role>
      </actor>
    </actors>
    <reviews>
      <review>
        <date>2010-07-16</date>
        <rating>9</rating>
        <text>Amazing movie!</text>
      </review>
      <review>
        <date>2011-01-01</date>
        <rating>8</rating>
        <text>Great visuals and story.</text>
      </review>
    </reviews>
  </movie>
</movies>
